version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ~/foodgram/.env
  
  web:
    image: yankovskayaktr/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ~/foodgram/.env

  frontend:
    build:
      context: ~/foodgram/frontend 
      dockerfile: Dockerfile 
    volumes:
      - ~/foodgram/frontend/:/app/result_build/
     
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ~/foodgram/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/foodgram/frontend/build:/usr/share/nginx/html/
      - ~/foodgram/docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ~/foodgram/docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
      - db
      - frontend
      

volumes:
  postgres_data:
  static_value:
  media_value: