# Generated by Django 3.0.5 on 2021-11-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('measurement_unit', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
