# Generated by Django 3.0.5 on 2021-12-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20211209_0134'),
        ('users', '0002_auto_20211209_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='is_favorited', to='recipes.Recipe', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='is_in_shopping_cart', to='recipes.Recipe', verbose_name='Список покупок'),
        ),
    ]
